project:
  type: website

website:
  title: "Antoine Tourret"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/antoine-tourret-b70672175/
      - icon: github
        href: https://github.com/Antoine-T17
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css


editor: visual