project:
  type: website
  output-dir: docs

website:
  title: "Antoine Tourret"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "Photos"
        file: photos.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/antoine-tourret-b70672175/
      - icon: github
        href: https://github.com/Antoine-T17
  back-to-top-navigation: true
  page-footer:
    border: true
    left: |
      © 2026 Antoine TOURRET.
      Content licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).
    right: "Made with Quarto"
format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css


editor: visual